cargo-features = ["test-dummy-unstable"]


[package]
name = "AurrasRust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "aurrasd"
path = "src/aurrasd.rs"

[dependencies]
libc = "0.2.126"
